version: '3'
services:
  nachi-trot-race:
    container_name: nachi-trot-race
    image: nachi-trot-race
    restart: always
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
